### ISSUE TITLE
Java not load data in SQL

### ISSUE THREAD

**Issue by ghost** [mahaupt/DCSServerStats#11]
Hi, I've been trying to get DCSServerStats to work for two days, but I can't get it to "upload" the data from the server to my SQL database. It gives me: HTTP Response code 500
![IMG_3752](https://user-images.githubusercontent.com/57815049/80867891-07fa0e80-8c97-11ea-9e8e-7518b45f519f.jpg)

**Comment by ghost** [comment]
I have noticed, if the bat password and the "secretpassword" in the config.inc.php file are EQUAL, it fails (ERROR 500) but if they are different, it gives code 200

**Comment by mahaupt** [comment]
Hi, HTTP response code 500 stands for internal server error. This is probably caused by an incorrectly set up web server or the php script itself. Can you provide us with the PHP error message?
Make sure you have the php-mysql plugin installed in your web server.

**Comment by ghost** [comment]
Hi, I don't see the PHP error. I use a Hostinger server, where I created the database (with the template) and uploaded the PHP. Maybe this is too big for me... But any help is welcome :-)

**Comment by ghost** [comment]
You'll forgive me, I must have had something wrong with the call to the database/configuration, now everything is operational. Thank you very much and sorry for the inconvenience
