### ISSUE TITLE
Tables Empty

### ISSUE THREAD

**Issue by acothebraco** [mahaupt/DCSServerStats#16]
Hello, sorry that i waste your time but i have a little problem on my Databese. The exporter exports very well with a success code HTTP 200 but some of my Tables in the Databease are Empty. The Other Think on the .jar file in the CMD Windows i can see Messages like:  **Received: 7595,S_EVENT_POSITION,16821506,blue,AIRPLANE,FA-18C_hornet,[VF-235] CatEye,No Weapon,No Weapon,0,655.26475363875,POSITION,36.231569161124,37.200715690979**

What do i wrong on the configuration?

**Comment by mahaupt** [comment]
Hi, can you confirm that the mysql settings in config.inc.php are correct?

**Comment by acothebraco** [comment]
Hi,

i checked the mysql settings in the config.inc.php an those are correct. The data comes in the Database but some Tables are empty. I attached a screenshot of my Database here. Should I do some configurations for the DCS Server for that? 
![DCS Server Stats](https://user-images.githubusercontent.com/80178563/112391116-aea82d00-8cf7-11eb-8704-96044edcb659.JPG)

**Comment by acothebraco** [comment]
Hello again, 

i fixed the issue. 

the error was in the line **dofile ('Scripts / ScriptingSystem.lua')** in the MissionScripting.lua.

In my MissionScripting.lua I had **dofile ('Scripts / ScriptingSystem.lua')** twice. Once at the beginning and what I copied. I removed one of the two and the program is now working. Thank you for your support.

**Comment by mahaupt** [comment]
I‘m glad it works now
