### ISSUE TITLE
DCS OpenBeta Server - No Position Data 

### ISSUE THREAD

**Issue by Shazzer1951** [mahaupt/DCSServerStats#17]
Hello, I am using "DCS OpenBeta Server" and I can not for the life of me get the position data to work..The Mission data is working.

-- All settings in the DCSServerStat files are unchanged except the bat file is pointed to my DB \ Web Server - "127.0.0.1 9182 http://**192.168.1.20**/DCSServerStats/entry.php "secretpassword"

Both the mission and position lua files are in "C:\Users\Administrator\Saved Games\ [HVY]Dedicated-005\Scripts" 
 - Created Export.lua C:\Users\Administrator\Saved Games\ [HVY]Dedicated-005\Scripts" (Copied it from my Open Beta Install)
 - Add "dofile(lfs.writedir()..'Scripts/DCSUDPPositionDataExport.lua')"

I dont see any errors in the DCS logs either....

Any Ideas?

[Export.zip](https://github.com/mahaupt/DCSServerStats/files/6681532/Export.zip)

**Comment by mahaupt** [comment]
Hi, from my point of view I assume that the Export.lua might not be loaded into the game.
Or DCS changed the API. 
Unfortunately, I can't assist you with troubleshooting because I don't have a windows machine to run dcs atm.

**Comment by Dragonius** [comment]
This Error was in DCS logs

2022-04-22 09:25:25.177 ERROR   Lua::Config: Call error LuaExportAfterNextFrame:[string "C:\Users\Black\Saved Games\DCS.server\Scripts/DCSUDPPositionDataExport.lua"]:59: attempt to concatenate local 'coalition' (a nil value)
stack traceback:
	[C]: ?
	[string "C:\Users\Black\Saved Games\DCS.server\Scripts/DCSUDPPositionDataExport.lua"]:59: in function 'Frame'
	[string "C:\Users\Black\Saved Games\DCS.server\Scripts/DCSUDPPositionDataExport.lua"]:79: in function <[string "C:\Users\Black\Saved Games\DCS.server\Scripts/DCSUDPPositionDataExport.lua"]:77>.

**Comment by Dragonius** [comment]
only resolution that i got working was that:
i added inside MissionScripting.lua 
dofile(lfs.writedir()..'Scripts/DCSUDPMissionDataExport.lua')

and made changes:

--do
--	sanitizeModule('os')
--	sanitizeModule('io')
--	sanitizeModule('lfs')
--	_G['require'] = nil
--	_G['loadlib'] = nil
--	_G['package'] = nil
--end

**Comment by Dragonius** [comment]
Also with 2.9 update
i did sanitize:

local function sanitizeModule(name)
	_G[name] = nil
	package.loaded[name] = nil
end

to

-- local function sanitizeModule(name)
-- 	_G[name] = nil
-- 	package.loaded[name] = nil
-- end

i recomment close this issue

**Comment by Dragonius** [comment]
> Hi, from my point of view I assume that the Export.lua might not be loaded into the game. Or DCS changed the API. Unfortunately, I can't assist you with troubleshooting because I don't have a windows machine to run dcs atm.

sorry i did steal threat, but if DCS cant load export files as it READS as default:

C:\Users\USERNAME\Saved Games\{DCS,DCS.openbeta,DCS.server}\Scripts

it can be pointed to other directories, but currently i think is only mklink-command

Also you have space on "es\ [HVY]Dedicated-005\S" 
That can be culprit also
