### ISSUE TITLE
Position data not working

### ISSUE THREAD

**Issue by V1irus** [mahaupt/DCSServerStats#7]
anyone there?

**Comment by sgraypgh** [comment]
Any support for this exceptional code. I have all working except position data.

**Comment by mahaupt** [comment]
Glad you like it! The position data is not working right now and needs a patch. If you like you can write a fix :)

**Comment by sgraypgh** [comment]
I wish I was as wise as you with coding. If you could point me in the right direction i will give it a go. I have added the lua reference to the missionscripting.lua, but not sure if i need a separate entry.php or what. Thanks for your quick reply Sir!

**Comment by engines-wafu** [comment]
> Glad you like it! The position data is not working right now and needs a patch. If you like you can write a fix :)

Hey @cbacon93,

I want to help out with the development of this part of the module.  I spent a few hours working with the code today, but couldn't figure out what the issues were.

Have you ever managed to get position data?

**Comment by mahaupt** [comment]
Yes, we managed to get the position data and view the flights via google maps. 
I haven't been able to look at the the code recently. I'm sorry!
The issue might be that the DCSUDPPositionDataExport.lua must be included in a file other than MissionScripting.lua. (I can't remember which one)

I will be quarantined the next few days at home, so I have some time figuring it out. Hang on guys!
