### ISSUE TITLE
What program you did use to compile java files?

### ISSUE THREAD

**Issue by Dragonius** [mahaupt/DCSServerStats#8]
i code in netbeans and i cant get build the jar file that dont scream that main class is missing.

I need some help. @cbacon93

**Comment by Dragonius** [comment]
Error: Could not find or load main class DCSServerStats

**Comment by mahaupt** [comment]
I dont know netbeans but using javac in the command line works.

**Comment by Dragonius** [comment]
can you give commandline that you make the jar file using javac 

thank you

**Comment by Dragonius** [comment]
jar cmf ./META-INF/MANIFEST.MF DCSTEST.jar ./dcsStats/DCSServerStats.class ./dcsStats/DCSServerStats\$HttpSendThread.class
