### ISSUE TITLE
Unit doesn't exist stack traceback

### ISSUE THREAD

**Issue by ravczyPL** [mahaupt/DCSServerStats#9]
DCSUDPMissionDataExport.lua:127: 

[C]: ?
[C]: in function 'getName'

**Comment by mahaupt** [comment]
Can you tell me how I can reproduce the error?

**Comment by ravczyPL** [comment]
I get very often when playing online on 2.5.6.  I failed to reproduce the deliberate consciously.  appears very often when I play with friends.  When the server is empty, the error does not appear

Pobierz aplikację Outlook dla systemu Android<https://aka.ms/ghei36>

________________________________

**Comment by mahaupt** [comment]
https://github.com/cbacon93/DCSServerStats/blob/060d026a1bd610a5e6941789c1ddaa7d05fee8c3/lua/DCSUDPMissionDataExport.lua#L127

This is the line, maybe the function is not available or the e.initiator is of a unexpected type. 
Or maybe the error is inside the getName() function.
